name: Cloud Security Suite CI
on: [push]

permissions:
  contents: read

jobs:
  secure-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Terraform Security Scan
        uses: bridgecrewio/checkov-action@master
        with:
          # Changed from '.' to your new folder path
          directory: projects/01-S3-Hardening
          framework: terraform

      - name: Docker Security Scan
        uses: bridgecrewio/checkov-action@master
        with:
          # Changed to your new Docker folder
          directory: projects/03-DevSecOps-CI-CD
          framework: dockerfile