name: Cloud Security Suite CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  secure-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          # IMPORTANT: Point this to your new project folder
          directory: projects/01-S3-Hardening
          framework: terraform
          quiet: true # Only show errors